### ISSUE TITLE
Just another Galacticraft issue

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/NewHorizons#168]
While leaving for the asteroid dimension, the rocket put me at a location 65000 blocks away from the normal coordinates. When coming back to the overworld it uses the same coords as the departure location so i ended up 65k blocks from the base, the new chunks started loading and apparently crashed the server. Aaaaand since if the server crashed while you are lading you lose your items from the parachest - lost a Tier III rocket (with 3 chests) and a set of rocket pads.
Huraaay for galacticraft

**Comment by Dream-Master** [comment]
You got an error?

**Comment by Drobac** [comment]
No error on my part, just disconnects/timed out of the server

**Comment by Dream-Master** [comment]
what time?

**Comment by Drobac** [comment]
Today at 13:20:48

**Comment by Drobac** [comment]
actuallyy 12:57:13 for the asteroids
