### ISSUE TITLE
Need Meterials for a cheaper Gt Item pipe (lower than Brass)

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/NewHorizons#187]
Any Suggestion?

**Comment by PaladinOne** [comment]
Given that GT item pipes work by teleporting item stacks, X stack per second based on pipe size, how would you make a lower tier pipe than Brass? Add seconds of delay between when items are teleported? Only teleport items 1 at a time in stead of 1 stack at a time?

Wood and Copper are already used for fluids... Tin maybe? Bismuth? Zinc? Brass is an alloy, so to be cheaper than Brass it should be just a natural metal.

**Comment by Dream-Master** [comment]
Thanks we adding tin pipes  for the lowest Tier.
